### ISSUE TITLE
Not working with mpv, "Couldn't find file"

### ISSUE THREAD

**Issue by bxkx** [Ajatt-Tools/autosubsync-mpv#4]
Hey, I'm on Arch with mpv version 0.34.0 and unfortunately autosubsync just doesn't want to work for me.

```
[autosubsync] Subtitle synchronization failed:
[autosubsync] Couldn't find file:///home/user/subtitle.srt 
```
Is what I'm getting every time. I start a video, load an external sub, hit n, then doesn't matter what method to sync I choose, the above message is all I get in the logs about it. The file definitely exists.

The weird thing is, thanks to this issue https://github.com/Ajatt-Tools/mpvacious/issues/53 I got autosubsync working with Celluloid too and it successfully syncs the subs there.

**Comment by tatsumoto-ren** [comment]
There's not much to go on. Do you happen to have more logs?

**Comment by bxkx** [comment]
Here's some more of the mpv log
[mpvoutput.txt](https://github.com/Ajatt-Tools/autosubsync-mpv/files/7741234/mpvoutput.txt)
